export type InputType =
  | "text"
  | "email"
  | "number"
  | "textarea"
  | "checkbox"
  | "date"
  | "file"
  | "select"
  | "multiselect"
  | "table"
  | "members"
  | "zoning"
  | "add_questionnaires"
  | "view_questionnaires";
