export type InputType =
  | "text"
  | "email"
  | "number"
  | "textarea"
  | "checkbox"
  | "date"
  | "file"
  | "select"
  | "multiselect"
  | "table"
  | "members"
  | "zoning"
  | "existing_land_use"
  | "proposed_land_use"
  | "report";
